### ISSUE TITLE
[ERROR] Few Files Missing

### ISSUE THREAD

**Issue by regiusherder** [duanxianpi/AI-Voice-Diary#2] opened 2023-08-24 10:03 UTC
The requirements.txt is missing and data/data.json is also missing

**Comment by krafi-code** [comment] 2023-11-14 05:29
any update ?? 

https://gitlab.com/krafi/git-backed-diary/-/tree/main?ref_type=heads
 (PYSIDE 6 )
i was thinking may i use the code in this project ?? 

but dont have any idea about this project

**Comment by krafi-code** [comment] 2023-11-14 05:38
alright without any idea i created a dir data and inside that dir a file data.json , the program shown qt widget like invalid json file.. any way my program run up,,

the issue is when i try to stop the voice record 

33.86941838264465
Traceback (most recent call last):
  File "/home/krafi.info/git-backed-diary/AI-Voice-Diary/mainwindow.py", line 81, in on_stopBtn_clicked
    self.recorder.stopRecording()
  File "/home/krafi.info/git-backed-diary/AI-Voice-Diary/record.py", line 42, in stopRecording
    self.wf.close()
    ^^^^^^^
AttributeError: 'record' object has no attribute 'wf'

**Comment by krafi-code** [comment] 2023-11-14 05:41
python3 mainwindow.py
[<PySide6.QtWidgets.QListWidgetItem object at 0x7fc23d552700>]
2023_11_14
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2675:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
2023_11_14
Exception in thread Thread-2 (record_audio):
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/krafi.info/git-backed-diary/AI-Voice-Diary/record.py", line 26, in record_audio
    self.wf = wave.open(wave_out_path, 'wb')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/wave.py", line 633, in open
    return Wave_write(f)
           ^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/wave.py", line 425, in __init__
    f = builtins.open(f, 'wb')
        ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/record/2023_11_14.wav'
Exception ignored in: <function Wave_write.__del__ at 0x7fc23e690f40>
Traceback (most recent call last):
  File "/usr/lib64/python3.11/wave.py", line 447, in __del__
    self.close()
  File "/usr/lib64/python3.11/wave.py", line 564, in close
    if self._file:
       ^^^^^^^^^^
AttributeError: 'Wave_write' object has no attribute '_file'
0.9510784149169922
1.9420335292816162
2.9421658515930176
3.9428207874298096
4.941879987716675
5.942338705062866
6.94172215461731
7.941643714904785
Traceback (most recent call last):
  File "/home/krafi.info/git-backed-diary/AI-Voice-Diary/mainwindow.py", line 81, in on_stopBtn_clicked
    self.recorder.stopRecording()
  File "/home/krafi.info/git-backed-diary/AI-Voice-Diary/record.py", line 42, in stopRecording
    self.wf.close()
    ^^^^^^^
AttributeError: 'record' object has no attribute 'wf'
8.94210958480835

**Comment by krafi-code** [comment] 2023-11-14 05:53
```
import os
    def record_audio(self, wave_out_path):
        try:
            print(wave_out_path)

            os.makedirs(os.path.dirname(wave_out_path), exist_ok=True)
            open(wave_out_path, 'a').close()
            self.stream = self.p.open(format=self.FORMAT,
                            channels=self.CHANNELS,
                            rate=self.RATE,
                            input=True,
                            frames_per_buffer=self.CHUNK)
            self.wf = wave.open(wave_out_path, 'wb')
            self.wf.setnchannels(self.CHANNELS)
            self.wf.setsampwidth(self.p.get_sample_size(self.FORMAT))
            self.wf.setframerate(self.RATE)
```

now the issue fixed but i dont know why after saveing it auto close , but the app is working , maybe this is how dev wanted to make ,, nah its my linux system issue i believe 

Expression 'alsa_snd_pcm_mmap_begin( self->pcm, &areas, &self->offset, numFrames )' 
failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3998
Expression 'PaAlsaStreamComponent_RegisterChannels( &self->capture, &self->bufferPro
cessor, &captureFrames, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line:
 4112
Expression 'PaAlsaStream_SetUpBuffers( stream, &framesGot, &xrun )' failed in 'src/h
ostapi/alsa/pa_linux_alsa.c', line: 4441
Exception in thread Thread-3 (record_audio):
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
[1]    25920 segmentation fault (core dumped)  python3 mainwindow.py


somekind of alsa issue

**Comment by krafi-code** [comment] 2023-11-14 05:58
i am seeing this program just a voice recorder , does it do voice to text ?? maybe its not working for some bug

**Comment by krafi-code** [comment] 2023-11-14 06:13
https://devpost.com/software/ai-voice-diary

thanks for  the video , now i am interested to do contribute your code , thats make sense  , thanks for your handwork, haha

**Comment by duanxianpi** [comment] 2023-11-14 06:57
Hello krafi, thanks for your interesting in this project. However, this project was done while I was participating in a 12-hours hackathon, so the code was terribly designed and lacked maintenance, so there may be some problems in running it. The Voice to Text part is provided by [Assembly AI](https://www.assemblyai.com/), I delete my api key in the code, you could replace it by yours. In addition, I believe they already updated their api, so you may need to check their doc.

**Comment by krafi-code** [comment] 2023-11-14 07:30
> Hello krafi, thanks for your interesting in this project. However, this project was done while I was participating in a 12-hours hackathon, so the code was terribly designed and lacked maintenance, so there may be some problems in running it. The Voice to Text part is provided by [Assembly AI](https://www.assemblyai.com/), I delete my api key in the code, you could replace it by yours. In addition, I believe they already updated their api, so you may need to check their doc.

hhmmm its normal you should not provide your api key , you should remove api key from that ai website as you cant remove anything from your old git commit , you should checkout my pyside6 dairy application , you will feel great i believe , well i dont have much big ai idea like your ,AssemblyAI donating your personal though to a proprietary Ai isn't it strange also privacy  thread  ? i was searching for an offline ai after seeing your project to make voice to text i found from pocketsphinx import LiveSpeech but it just so bad to translate . . what do you think ?

**Comment by duanxianpi** [comment] 2023-11-14 07:43
You are absolutely right! We do need to consider the privacy. For the offline speech recognition, you may try [Whisper](https://github.com/openai/whisper). It was published by OpenAI and can run offline. 

If you don't have any question for this project, I will close this issue.  If you have any question for me, you could reach out me by my email duanxianpi@gmail.com

**Comment by krafi-code** [comment] 2023-11-14 12:06
sorry bro i just tell me a truth  , i was downloading whisper it tool about `pip install -U openai-whisper` for this it took almost 4GB ,

` whisper a.mp3 --model medium `  for medium model it took 1.42G 
also  tried large model it took 3 GB you 

you should think will  user want to give this 6-9gb storage for this task ? or should i build my own server side. user should have both option maybe . thats it ,no more question have a great day but its good really whisper .
also good news  is i dont have cuda still i was able to do it.

you talk about monitoring emotion thats more interesting if its possible in reality .
https://www.youtube.com/watch?v=S2wnqc09PfQ&ab_channel=techinfowithkrafi

oh and before closing this just update on  "AI-Voice-Diary/record.py"

```
import os
    def record_audio(self, wave_out_path):
        try:
            print(wave_out_path)

            os.makedirs(os.path.dirname(wave_out_path), exist_ok=True)
            open(wave_out_path, 'a').close()
```
add empty dir and file,,,, `data/data.json `

**Closed as completed** 2023-11-14 18:28 UTC
